# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MJRefreshTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
     pod 'MJRefresh', '~> 3.1.15.3'
     pod 'hprose'
  # Pods for MJRefreshTest

end
