# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDBTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMDBTest
pod 'FMDB/SQLCipher'
end
