# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XLFormTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'XLForm', '~> 4.0.0'
pod 'Masonry','~>1.1.0'
pod 'ACMediaFrame'
  # Pods for XLFormTest

end
