# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cell高度自适应' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
    pod 'hprose', '2.0.2'
    pod 'YYModel', '~> 1.0.4'
    pod 'Masonry', '~> 1.1.0'
    pod 'SDWebImage', '~> 4.3.3'
  # Pods for Cell高度自适应

end
